In [4]:
import pandas as pd

print('pandas is ready')
print("version:", pd.__version__)

pandas is ready
version: 3.0.3

In [7]:
data = {"name": ["John", "Sara", "Mike", "Lisa", "Tom"],
        "age": [25,      34,     28,     45,     31], 
        "city": ["Toronto", "Waterloo", "Hamilton", "Toronto", "Waterloo"], 
        "monthly-bill": [65,      85,     45,     90,     55], 
        "churned": ["No",    "Yes",  "No",   "Yes",  "No"]}

df = pd.DataFrame(data)

In [8]:
df

   name  age      city  monthly-bill churned
0  John   25   Toronto            65      No
1  Sara   34  Waterloo            85     Yes
2  Mike   28  Hamilton            45      No
3  Lisa   45   Toronto            90     Yes
4   Tom   31  Waterloo            55      No

In [9]:
df.shape

(5, 5)

In [12]:
df.head(2)

   name  age      city  monthly-bill churned
0  John   25   Toronto            65      No
1  Sara   34  Waterloo            85     Yes

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          5 non-null      str
 1   age           5 non-null      int64
 2   city          5 non-null      str
 3   monthly-bill  5 non-null      int64
 4   churned       5 non-null      str
dtypes: int64(2), str(3)
memory usage: 332.0 bytes

In [19]:
df.describe()

             age  monthly-bill
count   5.000000      5.000000
mean   32.600000     68.000000
std     7.700649     19.235384
min    25.000000     45.000000
25%    28.000000     55.000000
50%    31.000000     65.000000
75%    34.000000     85.000000
max    45.000000     90.000000

In [20]:
df.isnull()

    name    age   city  monthly-bill  churned
0  False  False  False         False    False
1  False  False  False         False    False
2  False  False  False         False    False
3  False  False  False         False    False
4  False  False  False         False    False

In [21]:
df.sum()

name                               JohnSaraMikeLisaTom
age                                                163
city            TorontoWaterlooHamiltonTorontoWaterloo
monthly-bill                                       340
churned                                   NoYesNoYesNo
dtype: object

In [22]:
df.isnull().sum()

name            0
age             0
city            0
monthly-bill    0
churned         0
dtype: int64

In [23]:
data2 = {"student": ["John", "Sara", "Mike", "Lisa", "Tom"],
        "Grade": [25,      34,     28,     45,     31],
         "Score": [65,      85,     45,     90,     55]}

df2 = pd.DataFrame(data2)

In [24]:
df2

  student  Grade  Score
0    John     25     65
1    Sara     34     85
2    Mike     28     45
3    Lisa     45     90
4     Tom     31     55

In [25]:
df2.describe()

           Grade      Score
count   5.000000   5.000000
mean   32.600000  68.000000
std     7.700649  19.235384
min    25.000000  45.000000
25%    28.000000  55.000000
50%    31.000000  65.000000
75%    34.000000  85.000000
max    45.000000  90.000000

In [26]:
df2.head(2)

  student  Grade  Score
0    John     25     65
1    Sara     34     85

In [27]:
df["age"]

0    25
1    34
2    28
3    45
4    31
Name: age, dtype: int64

In [28]:
df[["age", "monthly-bill"]]

   age  monthly-bill
0   25            65
1   34            85
2   28            45
3   45            90
4   31            55

In [29]:
df[df["churned"] == "Yes"]

   name  age      city  monthly-bill churned
1  Sara   34  Waterloo            85     Yes
3  Lisa   45   Toronto            90     Yes

In [30]:
df[df["monthly-bill"] > 60]

   name  age      city  monthly-bill churned
0  John   25   Toronto            65      No
1  Sara   34  Waterloo            85     Yes
3  Lisa   45   Toronto            90     Yes

In [32]:
df["isexpensive"] = df["monthly-bill"] > 70

In [33]:
df

   name  age      city  monthly-bill churned  isexpensive
0  John   25   Toronto            65      No        False
1  Sara   34  Waterloo            85     Yes         True
2  Mike   28  Hamilton            45      No        False
3  Lisa   45   Toronto            90     Yes         True
4   Tom   31  Waterloo            55      No        False

In [35]:
X = df[["age", "monthly-bill"]]
Y = df["churned"]

print("Features X :")
print(X)
print("\nFeatures Y :")
print(Y)

Features X :
   age  monthly-bill
0   25            65
1   34            85
2   28            45
3   45            90
4   31            55

Features Y :
0     No
1    Yes
2     No
3    Yes
4     No
Name: churned, dtype: str

In [38]:
y = df["churned"].map({"Yes": 1, "No": 0})


print(y)
print("\n DataType Now ", y.dtype)

0    0
1    1
2    0
3    1
4    0
Name: churned, dtype: int64

 DataType Now  int64

In [43]:
from sklearn.model_selection import train_test_split

print("Skikit-learnn is ready!")

Skikit-learnn is ready!

In [44]:
from sklearn.model_selection import train_test_split

print("Skikit-learnn is ready!")

Skikit-learnn is ready!

In [54]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 4
Testing rows: 1

In [56]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 100, random_state = 42)

model.fit(X_train, y_train)


print("Model Trained Successfulluy!")

Model Trained Successfulluy!

In [58]:
prediction = model.predict(X_test)

print("Model Prediction:", prediction)

print("Real Answer:", y_test.values)


print("Correct?", prediction == y_test.values)

Model Prediction: ['No']
Real Answer: <StringArray>
['Yes']
Length: 1, dtype: str
Correct? [False]

In [64]:
import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Total Rows: 7043
Total Columns: 21

In [65]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [67]:
print("=== SHAPE ===")
print(f"Rows:{df.shape[0]} , Columns: {df.shape[1]}")

print("\n=== COLUMN DATA TYPES ===")
print(df.dtypes)

print("\n=== MISSING VALUES (Null Analysis) ===")
print(df.isnull().sum())


print("\n=== TARGET VARIABLE DISTRIBUTION ===")
print(df["Churn"].value_counts())

=== SHAPE ===
Rows:7043 , Columns: 21

=== COLUMN DATA TYPES ===
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

=== MISSING VALUES (Null Analysis) ===
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

=== TARGET VARIABLE DISTRIBUTION ===
Churn
No     5174
Yes    1869
Name: count, dtype: int64
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [70]:
print("=== TotalCharges Sample Values ===")
print(df["TotalCharges"].head(10))


print("\n=== Finding Hidden Missing Values ===")
empty_charges = df[df["TotalCharges"].str.strip() == ""]
print(f"Rows with Empty charges: {len(empty_charges)}", )

=== TotalCharges Sample Values ===
0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: str

=== Finding Hidden Missing Values ===
Rows with Empty charges: 11

In [77]:
print("\n=== Fixing TotalCharges ===")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors = "coerce")
print("TotalCharges DataType Now: ", df["TotalCharges"].dtype)

=== Fixing TotalCharges ===
TotalCharges DataType Now:  float64

In [81]:
print("Missing values now: ", df["TotalCharges"].isnull().sum())

Missing values now:  11

In [82]:
print("Rows BEFORE dropping:", len(df))

Rows BEFORE dropping: 7043

In [83]:
df = df.dropna(subset = ["TotalCharges"])

In [86]:
print("Rows After Dropping: ", len(df))

Rows After Dropping:  7032

In [90]:
print("All colums:")

for col in df.columns:
    print(f"{col} -> {df[col].dtype}")

All colums:
customerID -> str
gender -> str
SeniorCitizen -> int64
Partner -> str
Dependents -> str
tenure -> int64
PhoneService -> str
MultipleLines -> str
InternetService -> str
OnlineSecurity -> str
OnlineBackup -> str
DeviceProtection -> str
TechSupport -> str
StreamingTV -> str
StreamingMovies -> str
Contract -> str
PaperlessBilling -> str
PaymentMethod -> str
MonthlyCharges -> float64
TotalCharges -> float64
Churn -> str

In [93]:
df = df.drop(columns = ["customerID"])

print("Customer ID is Dropped!")

print("remainning Columns:", df.shape[1])

Customer ID is Dropped!
remainning Columns: 20

In [102]:
binary_columns = ["Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]

for col in binary_columns:
    df[col] = df[col].map({"Yes": 1, "No": 0})

print("Binary Encoding is Done!")
print(df[binary_columns].head())

Binary Encoding is Done!
   Partner  Dependents  PhoneService  PaperlessBilling  Churn
0        1           0             0                 1      0
1        0           0             1                 0      0
2        0           0             1                 1      1
3        0           0             0                 0      0
4        0           0             1                 1      1

In [105]:
print(df.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [115]:
import pandas as pd
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df = df.dropna(subset=["TotalCharges"])
df = df.drop(columns=["customerID"])
binary_columns = ["Partner", "Dependents", "PhoneService",
                  "PaperlessBilling", "Churn"]
for col in binary_columns:
    df[col] = df[col].map({"Yes": 1, "No": 0})


df = pd.get_dummies(df, columns = [
    "gender",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"], drop_first = True)

print("One hot Coding is done!")
print("Total Columns Now:", df.shape[1])
print("\nAll Columns after Encoding:")
print(df.columns.tolist())

One hot Coding is done!
Total Columns Now: 31

All Columns after Encoding:
['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn', 'gender_Male', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [116]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


X = df.drop(columns = ["Churn"])
Y = df["Churn"]


print("Feature Shape:", X.shape)
print("Target Shape:", Y.shape)

Feature Shape: (7032, 30)
Target Shape: (7032,)

In [119]:
X.columns.tolist()

['SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'PaperlessBilling',
 'MonthlyCharges',
 'TotalCharges',
 'gender_Male',
 'MultipleLines_No phone service',
 'MultipleLines_Yes',
 'InternetService_Fiber optic',
 'InternetService_No',
 'OnlineSecurity_No internet service',
 'OnlineSecurity_Yes',
 'OnlineBackup_No internet service',
 'OnlineBackup_Yes',
 'DeviceProtection_No internet service',
 'DeviceProtection_Yes',
 'TechSupport_No internet service',
 'TechSupport_Yes',
 'StreamingTV_No internet service',
 'StreamingTV_Yes',
 'StreamingMovies_No internet service',
 'StreamingMovies_Yes',
 'Contract_One year',
 'Contract_Two year',
 'PaymentMethod_Credit card (automatic)',
 'PaymentMethod_Electronic check',
 'PaymentMethod_Mailed check']

In [120]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

print("Trainning Rows: ", len(X_train))
print("Test Rows:", len(X_test))

Trainning Rows:  5625
Test Rows: 1407

In [3]:
model = RandomForestClassifier(n_estimators = 100, random_state = 42)

model.fit(X_train, Y_train)

print("Model Trainned on Real Data!!")

NameError: name 'RandomForestClassifier' is not defined

In [4]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


y_predict = model.predict(X_test)

accuracy = accuracy_score(Y_test, y_predict)
print(f"Accuracy: {accuracy}")

NameError: name 'model' is not defined

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             confusion_matrix)


df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
print("Data loaded:", df.shape)

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

df = df.dropna(subset=["TotalCharges"])

df = df.drop(columns=["customerID"])

binary_columns = ["Partner", "Dependents", "PhoneService",
                  "PaperlessBilling", "Churn"]
for col in binary_columns:
    df[col] = df[col].map({"Yes": 1, "No": 0})


df = pd.get_dummies(df, columns=[
    "gender", "MultipleLines", "InternetService",
    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies",
    "Contract", "PaymentMethod"
], drop_first=True)


print("Preprocessing done:", df.shape)

X = df.drop(columns=["Churn"])
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
print("Model trained successfully!")


y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"\n Accuracy: {accuracy * 100:.2f}%")

Data loaded: (7043, 21)
Preprocessing done: (7032, 31)
Training rows: 5625
Testing rows: 1407
Model trained successfully!

 Accuracy: 78.39%

In [6]:
print("\n Classification Report:")
print(classification_report(y_test, y_pred))

 Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1033
           1       0.63      0.45      0.53       374

    accuracy                           0.78      1407
   macro avg       0.73      0.68      0.69      1407
weighted avg       0.77      0.78      0.77      1407

In [7]:
print("\n Confussion Matrix")
print(confusion_matrix(y_test, y_pred))

 Confussion Matrix
[[933 100]
 [204 170]]

In [8]:
import joblib


joblib.dump(model, "churn-model.pkl")
print("Model saved as churn-model.pkl Successfully")

Model saved as churn-model.pkl Successfully

In [10]:
columns = X_train.columns.tolist()

In [11]:
print("columns")

columns

In [12]:
print(columns)

['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [13]:
import json

with open("model-columns.json", "w") as f:
    json.dump(columns, f)

print("Columns name model-columns.json successfully!! ")
print(f"Total feature saved {len(columns)}")

Columns name model-columns.json successfully!!
Total feature saved 30

AttributeError: 'list' object has no attribute 'dtypes'

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib
import json

# Load and preprocess
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df = df.dropna(subset=["TotalCharges"])
df = df.drop(columns=["customerID"])

binary_columns = ["Partner", "Dependents", "PhoneService",
                  "PaperlessBilling", "Churn"]
for col in binary_columns:
    df[col] = df[col].map({"Yes": 1, "No": 0})

df = pd.get_dummies(df, columns=[
    "gender", "MultipleLines", "InternetService",
    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies",
    "Contract", "PaymentMethod"
], drop_first=True)

# Train
X = df.drop(columns=["Churn"])
y = df["Churn"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Save fresh model!
joblib.dump(model, "churn-model.pkl")

columns = X_train.columns.tolist()
with open("model-columns.json", "w") as f:
    json.dump(columns, f)

print("Model retrained and saved!")

Model retrained and saved!